### ISSUE TITLE
Java Naming Conventions

### ISSUE THREAD

**Issue by mpmenne** [MichaelGordonII/JavaCS50#1]
Hi Michael,

Be sure to always follow [Java naming conventions](http://www.oracle.com/technetwork/java/codeconventions-135099.html), specifically make classes Capitalized and variables and methods start with a lower case letter.

Capitalizing methods might cause some people to think you are a .NET developer and you don't want that ;-)

Cheers!

**Comment by MichaelGordonII** [comment]
Made proper changes in Pset2. Thanks for the advice.
