### ISSUE TITLE
Use StringBuilder

### ISSUE THREAD

**Issue by mpmenne** [MichaelGordonII/JavaCS50#2]
Hey Michael,

Check out this [video about Strings in Java](http://tv.launchcode.us/#/videos/java_strings_performance?lesson=Java).

String are special in Java because they are final.  Anytime you concatenate two strings together (string1 + string2) it produces a new String.  For a small example like this it is less important, but imagine if our pyramid was 1,000,000 levels tall.  We would produce a lot of String objects that would need to be immediately garbage collected.  StringBuilder helps with this.

Cheers,

**Comment by mpmenne** [comment]
Feel free to close these when you are done with them

**Comment by MichaelGordonII** [comment]
Though not good practice, I've decided to leave this be until Pset3 when I implement the Pyramid class as I would need to rework the building and printing of the Pyramid anyways.
