### ISSUE TITLE
Keep it Dry

### ISSUE THREAD

**Issue by mpmenne** [MichaelGordonII/JavaCS50#4]
I noticed there is duplicated logic in OutputToConsole class and the OutputToFile class.

There is an axiom in software development called DRY which stands for "Do not Repeat Yourself".  The reason is that anytime there is duplicated code in a codebase, there is a significant chance of a bug being introduced in that code in the future.  It will be difficult to make sure that both files get updated.

See if you can reduce your duplication by refactoring the pyramid building logic.  It feels like the OutToConsole and OutputToFile are doing two things... building a pyramid and printing; maybe they can just do the printing.

**Comment by MichaelGordonII** [comment]
Another one where I was going to wait until Pset3. Though now that you said it, my functions do seem to do two things instead of one. That is not good. I will definitely change that in Pset3
